### ISSUE TITLE
Font issue in Linux

### ISSUE THREAD

**Issue by cactiCode** [nickersonm/nazca-design#1]
Hi, There is an issue with msilib in Linux environments

 File "/home/brunsviken/.local/lib/python3.11/site-packages/nazca/netlist.py", line 27, in <module>
    from msilib.schema import Font
ModuleNotFoundError: No module named 'msilib'

However is this module used at all?, since font is included further down
with : import nazca.font as font

**Comment by nickersonm** [comment]
You are correct: this module does not appear to be used at all. I have added a commit that removes this.
